version: '3.8'

services:
  web:
    build: .
    container_name: turizm_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - PYTHONUNBUFFERED=1
    # Agar kerak bo‘lsa, custom envlar, va boshqalar
