version: "3.8"

services:
  web:
    build: .
    container_name: turizm_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: turizm_redis
    expose:
      - "6379"

  nginx:
    image: nginx:latest
    container_name: turizm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf    # nginx config
      - ./static:/app/static
      - ./media:/app/media
      - ./certbot/conf:/etc/letsencrypt                      # letsencrypt certs
      - ./certbot/www:/var/www/certbot                       # acme-challenge
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
