# Generated by Django 5.0.1 on 2025-06-12 22:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Company History',
                'verbose_name_plural': 'Company History',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('role_en', models.CharField(max_length=100, null=True, verbose_name='Role')),
                ('role_ru', models.CharField(max_length=100, null=True, verbose_name='Role')),
                ('role_uz', models.CharField(max_length=100, null=True, verbose_name='Role')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Bio')),
                ('bio_en', ckeditor.fields.RichTextField(null=True, verbose_name='Bio')),
                ('bio_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Bio')),
                ('bio_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Bio')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Image')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
